apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wilapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Borex5r3/adbaich.git 
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
